# Generated by Django 2.0.2 on 2018-02-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliver_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliver_to',
        ),
    ]
