# Generated by Django 2.0.2 on 2018-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maistas', '0003_auto_20180219_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_to_lat', models.FloatField()),
                ('deliver_to_long', models.FloatField()),
                ('current_delivery_lat', models.FloatField()),
                ('current_delivery_long', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
