# Generated by Django 2.0.2 on 2018-02-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maistas', '0005_auto_20180219_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='maistas.Food'),
        ),
    ]
