# Generated by Django 2.0.2 on 2018-02-21 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maistas', '0007_auto_20180219_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
