# Generated by Django 2.0.2 on 2018-02-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maistas', '0008_auto_20180221_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_delivery_lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_delivery_long',
            field=models.FloatField(default=None, null=True),
        ),
    ]
